site_name: Video Streaming API
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand

plugins:
    - search
    - mermaid2

nav:
  - Home: index.md
  - Instalação: installation.md
  - API:
      - Visão Geral: api.md
      - Endpoints: endpoints.md
  - Arquitetura: architecture.md
  - Sobre: about.md